# Generated by Django 3.1.4 on 2020-12-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(max_length=100)),
                ('display', models.BooleanField(default=False)),
                ('picture_image', models.ImageField(max_length=500, upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('product_category', models.CharField(blank=True, choices=[('GENERAL', 'GENERAL'), ('PHONES', 'PHONES'), ('COMPUTERS', 'COMPUTERS'), ('PRINTERS', 'PRINTERS')], max_length=100, null=True)),
                ('main_page', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('product_image', models.ImageField(max_length=500, upload_to='products/')),
            ],
        ),
    ]
